/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpToolsRouteImport } from './routes/mcp-tools'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthProjectsRouteImport } from './routes/_auth/projects'
import { Route as AuthAgentsRouteImport } from './routes/_auth/agents'
import { Route as AuthProjectsIndexRouteImport } from './routes/_auth/projects/index'
import { Route as AuthAgentsIndexRouteImport } from './routes/_auth/agents/index'
import { Route as AuthPPubkeyRouteImport } from './routes/_auth/p/$pubkey'
import { Route as AuthLessonLessonIdRouteImport } from './routes/_auth/lesson.$lessonId'
import { Route as AuthChatEventIdRouteImport } from './routes/_auth/chat/$eventId'
import { Route as AuthAgentsRequestsRouteImport } from './routes/_auth/agents/requests'
import { Route as AuthAgentsPacksRouteImport } from './routes/_auth/agents/packs'
import { Route as AuthAgentDefinitionAgentDefinitionEventIdRouteImport } from './routes/_auth/agent-definition/$agentDefinitionEventId'
import { Route as AuthProjectsProjectIdIndexRouteImport } from './routes/_auth/projects/$projectId/index'
import { Route as AuthAgentsPacksIndexRouteImport } from './routes/_auth/agents/packs/index'
import { Route as AuthProjectsProjectIdSettingsRouteImport } from './routes/_auth/projects/$projectId/settings'
import { Route as AuthAgentsPacksNaddrRouteImport } from './routes/_auth/agents/packs/$naddr'

const McpToolsRoute = McpToolsRouteImport.update({
  id: '/mcp-tools',
  path: '/mcp-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsRoute = AuthProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsRoute = AuthAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthProjectsRoute,
} as any)
const AuthAgentsIndexRoute = AuthAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAgentsRoute,
} as any)
const AuthPPubkeyRoute = AuthPPubkeyRouteImport.update({
  id: '/p/$pubkey',
  path: '/p/$pubkey',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLessonLessonIdRoute = AuthLessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatEventIdRoute = AuthChatEventIdRouteImport.update({
  id: '/chat/$eventId',
  path: '/chat/$eventId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsRequestsRoute = AuthAgentsRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthAgentsRoute,
} as any)
const AuthAgentsPacksRoute = AuthAgentsPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => AuthAgentsRoute,
} as any)
const AuthAgentDefinitionAgentDefinitionEventIdRoute =
  AuthAgentDefinitionAgentDefinitionEventIdRouteImport.update({
    id: '/agent-definition/$agentDefinitionEventId',
    path: '/agent-definition/$agentDefinitionEventId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProjectsProjectIdIndexRoute =
  AuthProjectsProjectIdIndexRouteImport.update({
    id: '/$projectId/',
    path: '/$projectId/',
    getParentRoute: () => AuthProjectsRoute,
  } as any)
const AuthAgentsPacksIndexRoute = AuthAgentsPacksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAgentsPacksRoute,
} as any)
const AuthProjectsProjectIdSettingsRoute =
  AuthProjectsProjectIdSettingsRouteImport.update({
    id: '/$projectId/settings',
    path: '/$projectId/settings',
    getParentRoute: () => AuthProjectsRoute,
  } as any)
const AuthAgentsPacksNaddrRoute = AuthAgentsPacksNaddrRouteImport.update({
  id: '/$naddr',
  path: '/$naddr',
  getParentRoute: () => AuthAgentsPacksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp-tools': typeof McpToolsRoute
  '/agents': typeof AuthAgentsRouteWithChildren
  '/projects': typeof AuthProjectsRouteWithChildren
  '/settings': typeof AuthSettingsRoute
  '/agent-definition/$agentDefinitionEventId': typeof AuthAgentDefinitionAgentDefinitionEventIdRoute
  '/agents/packs': typeof AuthAgentsPacksRouteWithChildren
  '/agents/requests': typeof AuthAgentsRequestsRoute
  '/chat/$eventId': typeof AuthChatEventIdRoute
  '/lesson/$lessonId': typeof AuthLessonLessonIdRoute
  '/p/$pubkey': typeof AuthPPubkeyRoute
  '/agents/': typeof AuthAgentsIndexRoute
  '/projects/': typeof AuthProjectsIndexRoute
  '/agents/packs/$naddr': typeof AuthAgentsPacksNaddrRoute
  '/projects/$projectId/settings': typeof AuthProjectsProjectIdSettingsRoute
  '/agents/packs/': typeof AuthAgentsPacksIndexRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp-tools': typeof McpToolsRoute
  '/settings': typeof AuthSettingsRoute
  '/agent-definition/$agentDefinitionEventId': typeof AuthAgentDefinitionAgentDefinitionEventIdRoute
  '/agents/requests': typeof AuthAgentsRequestsRoute
  '/chat/$eventId': typeof AuthChatEventIdRoute
  '/lesson/$lessonId': typeof AuthLessonLessonIdRoute
  '/p/$pubkey': typeof AuthPPubkeyRoute
  '/agents': typeof AuthAgentsIndexRoute
  '/projects': typeof AuthProjectsIndexRoute
  '/agents/packs/$naddr': typeof AuthAgentsPacksNaddrRoute
  '/projects/$projectId/settings': typeof AuthProjectsProjectIdSettingsRoute
  '/agents/packs': typeof AuthAgentsPacksIndexRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp-tools': typeof McpToolsRoute
  '/_auth/agents': typeof AuthAgentsRouteWithChildren
  '/_auth/projects': typeof AuthProjectsRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/agent-definition/$agentDefinitionEventId': typeof AuthAgentDefinitionAgentDefinitionEventIdRoute
  '/_auth/agents/packs': typeof AuthAgentsPacksRouteWithChildren
  '/_auth/agents/requests': typeof AuthAgentsRequestsRoute
  '/_auth/chat/$eventId': typeof AuthChatEventIdRoute
  '/_auth/lesson/$lessonId': typeof AuthLessonLessonIdRoute
  '/_auth/p/$pubkey': typeof AuthPPubkeyRoute
  '/_auth/agents/': typeof AuthAgentsIndexRoute
  '/_auth/projects/': typeof AuthProjectsIndexRoute
  '/_auth/agents/packs/$naddr': typeof AuthAgentsPacksNaddrRoute
  '/_auth/projects/$projectId/settings': typeof AuthProjectsProjectIdSettingsRoute
  '/_auth/agents/packs/': typeof AuthAgentsPacksIndexRoute
  '/_auth/projects/$projectId/': typeof AuthProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp-tools'
    | '/agents'
    | '/projects'
    | '/settings'
    | '/agent-definition/$agentDefinitionEventId'
    | '/agents/packs'
    | '/agents/requests'
    | '/chat/$eventId'
    | '/lesson/$lessonId'
    | '/p/$pubkey'
    | '/agents/'
    | '/projects/'
    | '/agents/packs/$naddr'
    | '/projects/$projectId/settings'
    | '/agents/packs/'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp-tools'
    | '/settings'
    | '/agent-definition/$agentDefinitionEventId'
    | '/agents/requests'
    | '/chat/$eventId'
    | '/lesson/$lessonId'
    | '/p/$pubkey'
    | '/agents'
    | '/projects'
    | '/agents/packs/$naddr'
    | '/projects/$projectId/settings'
    | '/agents/packs'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/mcp-tools'
    | '/_auth/agents'
    | '/_auth/projects'
    | '/_auth/settings'
    | '/_auth/agent-definition/$agentDefinitionEventId'
    | '/_auth/agents/packs'
    | '/_auth/agents/requests'
    | '/_auth/chat/$eventId'
    | '/_auth/lesson/$lessonId'
    | '/_auth/p/$pubkey'
    | '/_auth/agents/'
    | '/_auth/projects/'
    | '/_auth/agents/packs/$naddr'
    | '/_auth/projects/$projectId/settings'
    | '/_auth/agents/packs/'
    | '/_auth/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpToolsRoute: typeof McpToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp-tools': {
      id: '/mcp-tools'
      path: '/mcp-tools'
      fullPath: '/mcp-tools'
      preLoaderRoute: typeof McpToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects': {
      id: '/_auth/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthProjectsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents': {
      id: '/_auth/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthAgentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/': {
      id: '/_auth/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthProjectsIndexRouteImport
      parentRoute: typeof AuthProjectsRoute
    }
    '/_auth/agents/': {
      id: '/_auth/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthAgentsIndexRouteImport
      parentRoute: typeof AuthAgentsRoute
    }
    '/_auth/p/$pubkey': {
      id: '/_auth/p/$pubkey'
      path: '/p/$pubkey'
      fullPath: '/p/$pubkey'
      preLoaderRoute: typeof AuthPPubkeyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/lesson/$lessonId': {
      id: '/_auth/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof AuthLessonLessonIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chat/$eventId': {
      id: '/_auth/chat/$eventId'
      path: '/chat/$eventId'
      fullPath: '/chat/$eventId'
      preLoaderRoute: typeof AuthChatEventIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/requests': {
      id: '/_auth/agents/requests'
      path: '/requests'
      fullPath: '/agents/requests'
      preLoaderRoute: typeof AuthAgentsRequestsRouteImport
      parentRoute: typeof AuthAgentsRoute
    }
    '/_auth/agents/packs': {
      id: '/_auth/agents/packs'
      path: '/packs'
      fullPath: '/agents/packs'
      preLoaderRoute: typeof AuthAgentsPacksRouteImport
      parentRoute: typeof AuthAgentsRoute
    }
    '/_auth/agent-definition/$agentDefinitionEventId': {
      id: '/_auth/agent-definition/$agentDefinitionEventId'
      path: '/agent-definition/$agentDefinitionEventId'
      fullPath: '/agent-definition/$agentDefinitionEventId'
      preLoaderRoute: typeof AuthAgentDefinitionAgentDefinitionEventIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$projectId/': {
      id: '/_auth/projects/$projectId/'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthProjectsRoute
    }
    '/_auth/agents/packs/': {
      id: '/_auth/agents/packs/'
      path: '/'
      fullPath: '/agents/packs/'
      preLoaderRoute: typeof AuthAgentsPacksIndexRouteImport
      parentRoute: typeof AuthAgentsPacksRoute
    }
    '/_auth/projects/$projectId/settings': {
      id: '/_auth/projects/$projectId/settings'
      path: '/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AuthProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthProjectsRoute
    }
    '/_auth/agents/packs/$naddr': {
      id: '/_auth/agents/packs/$naddr'
      path: '/$naddr'
      fullPath: '/agents/packs/$naddr'
      preLoaderRoute: typeof AuthAgentsPacksNaddrRouteImport
      parentRoute: typeof AuthAgentsPacksRoute
    }
  }
}

interface AuthAgentsPacksRouteChildren {
  AuthAgentsPacksNaddrRoute: typeof AuthAgentsPacksNaddrRoute
  AuthAgentsPacksIndexRoute: typeof AuthAgentsPacksIndexRoute
}

const AuthAgentsPacksRouteChildren: AuthAgentsPacksRouteChildren = {
  AuthAgentsPacksNaddrRoute: AuthAgentsPacksNaddrRoute,
  AuthAgentsPacksIndexRoute: AuthAgentsPacksIndexRoute,
}

const AuthAgentsPacksRouteWithChildren = AuthAgentsPacksRoute._addFileChildren(
  AuthAgentsPacksRouteChildren,
)

interface AuthAgentsRouteChildren {
  AuthAgentsPacksRoute: typeof AuthAgentsPacksRouteWithChildren
  AuthAgentsRequestsRoute: typeof AuthAgentsRequestsRoute
  AuthAgentsIndexRoute: typeof AuthAgentsIndexRoute
}

const AuthAgentsRouteChildren: AuthAgentsRouteChildren = {
  AuthAgentsPacksRoute: AuthAgentsPacksRouteWithChildren,
  AuthAgentsRequestsRoute: AuthAgentsRequestsRoute,
  AuthAgentsIndexRoute: AuthAgentsIndexRoute,
}

const AuthAgentsRouteWithChildren = AuthAgentsRoute._addFileChildren(
  AuthAgentsRouteChildren,
)

interface AuthProjectsRouteChildren {
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute
  AuthProjectsProjectIdSettingsRoute: typeof AuthProjectsProjectIdSettingsRoute
  AuthProjectsProjectIdIndexRoute: typeof AuthProjectsProjectIdIndexRoute
}

const AuthProjectsRouteChildren: AuthProjectsRouteChildren = {
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
  AuthProjectsProjectIdSettingsRoute: AuthProjectsProjectIdSettingsRoute,
  AuthProjectsProjectIdIndexRoute: AuthProjectsProjectIdIndexRoute,
}

const AuthProjectsRouteWithChildren = AuthProjectsRoute._addFileChildren(
  AuthProjectsRouteChildren,
)

interface AuthRouteChildren {
  AuthAgentsRoute: typeof AuthAgentsRouteWithChildren
  AuthProjectsRoute: typeof AuthProjectsRouteWithChildren
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthAgentDefinitionAgentDefinitionEventIdRoute: typeof AuthAgentDefinitionAgentDefinitionEventIdRoute
  AuthChatEventIdRoute: typeof AuthChatEventIdRoute
  AuthLessonLessonIdRoute: typeof AuthLessonLessonIdRoute
  AuthPPubkeyRoute: typeof AuthPPubkeyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAgentsRoute: AuthAgentsRouteWithChildren,
  AuthProjectsRoute: AuthProjectsRouteWithChildren,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthAgentDefinitionAgentDefinitionEventIdRoute:
    AuthAgentDefinitionAgentDefinitionEventIdRoute,
  AuthChatEventIdRoute: AuthChatEventIdRoute,
  AuthLessonLessonIdRoute: AuthLessonLessonIdRoute,
  AuthPPubkeyRoute: AuthPPubkeyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  McpToolsRoute: McpToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
